# Generated by Django 4.2.21 on 2025-05-17 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionresult',
            name='user_input',
            field=models.TextField(blank=True, null=True),
        ),
    ]
